### ISSUE TITLE
Support for nested list

### ISSUE THREAD

**Issue by SpokieKid** [mgmeyers/obsidian-copy-block-link#10]
Hi, I'm wondering if nested list like the following:
![image](https://user-images.githubusercontent.com/15869754/138705408-7514323b-f322-493c-b857-2d035ce0903c.png)
I've tried but seems the plugin does not support copy link embedded in this circumstances？

**Comment by mgmeyers** [comment]
@SpokieKid Are you wanting to copy a link to the entire list or just to a list item?

**Comment by SpokieKid** [comment]
I no longer have this issue, I will close this issue now. Thanks!
