### ISSUE TITLE
Request: Hide reference ^code in new live edit mode

### ISSUE THREAD

**Issue by ClandestineClout** [mgmeyers/obsidian-copy-block-link#16]
I love that the code hides in preview mode. But it doesn't seem to hide when the paragraph loses focus the way markdown does in live edit mode. Is there any way to make that happen?

**Comment by mgmeyers** [comment]
@ClandestineClout This isn't quite in the scope of this plugin, but I believe you could accomplish this with CSS. Maybe ask around in the obsidian discord or on the obsidian forums?
