### ISSUE TITLE
[Feature Request] Hotkey for Menu Context (mouse right click)

### ISSUE THREAD

**Issue by FelipeRearden** [mgmeyers/obsidian-copy-block-link#7]
Hello @mgmeyers !!!

First of all, thank you very much for this plug-in! My FR is related to the core feature of this plug-in :)

My FR is very simple: A hotkey to the mouse right click (Open Context Menu)

### Why I'm requesting this ?

Unfortunately, MacOS don't have dedicated keyboard key to do mouse right click. If you search on Google it is not very simple to do in MacOS :(

This way, I really need a hotkey to access the Context Menu in Obsidian :)

Thanks for reading this!

Have a great day!

**Comment by pjeby** [comment]
Actually, just having an obsidian command to copy the link would be nice, for those of us who love our keyboards.  :wink:  (It'd also be possible to make it a hotkey then.)

**Comment by FelipeRearden** [comment]
100% agree with you @pjeby ! 
Would be amazing to have the plug-in commands in command palette for our hotkeys workflow :)

By the way, I recently discover Quick Explorer and It’s a game changer for me! Thanks for creating it :)

**Comment by mgmeyers** [comment]
To commands were added in the latest release! Let me know if you encounter any issues with these.

<img width="714" alt="Screen Shot 2021-08-31 at 1 11 38 PM" src="https://user-images.githubusercontent.com/2694747/131569371-2bda66ef-9c52-48f0-9616-89efb3a05d24.png">

**Comment by FelipeRearden** [comment]
@mgmeyers 

thank you very much for this new features ! I tested and works perfect !!! 

Have a great day :)
